"""init schema

Revision ID: 74ee1818bd42
Revises:
Create Date: 2025-10-07 12:40:12.492096

"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "74ee1818bd42"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """执行升级操作"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apl_configs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("create_time", sa.String(length=32), nullable=False),
        sa.Column("latest_change_time", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_configs",
        sa.Column("config_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("config_name", sa.String(length=255), nullable=False),
        sa.Column("weapon", sa.String(length=255), nullable=False),
        sa.Column("weapon_level", sa.Integer(), nullable=False),
        sa.Column("cinema", sa.Integer(), nullable=False),
        sa.Column("crit_balancing", sa.Boolean(), nullable=False),
        sa.Column("crit_rate_limit", sa.Float(), nullable=False),
        sa.Column("scATK_percent", sa.Integer(), nullable=False),
        sa.Column("scATK", sa.Integer(), nullable=False),
        sa.Column("scHP_percent", sa.Integer(), nullable=False),
        sa.Column("scHP", sa.Integer(), nullable=False),
        sa.Column("scDEF_percent", sa.Integer(), nullable=False),
        sa.Column("scDEF", sa.Integer(), nullable=False),
        sa.Column("scAnomalyProficiency", sa.Integer(), nullable=False),
        sa.Column("scPEN", sa.Integer(), nullable=False),
        sa.Column("scCRIT", sa.Integer(), nullable=False),
        sa.Column("scCRIT_DMG", sa.Integer(), nullable=False),
        sa.Column("drive4", sa.Text(), nullable=False),
        sa.Column("drive5", sa.Text(), nullable=False),
        sa.Column("drive6", sa.Text(), nullable=False),
        sa.Column("equip_style", sa.String(length=255), nullable=False),
        sa.Column("equip_set4", sa.String(length=255), nullable=True),
        sa.Column("equip_set2_a", sa.String(length=255), nullable=True),
        sa.Column("equip_set2_b", sa.String(length=255), nullable=True),
        sa.Column("equip_set2_c", sa.String(length=255), nullable=True),
        sa.Column("create_time", sa.String(length=32), nullable=False),
        sa.Column("update_time", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("config_id"),
    )
    op.create_table(
        "enemy_configs",
        sa.Column("config_id", sa.String(length=128), nullable=False),
        sa.Column("enemy_index", sa.Integer(), nullable=False),
        sa.Column("enemy_adjust", sa.Text(), nullable=False),
        sa.Column("create_time", sa.String(length=32), nullable=False),
        sa.Column("update_time", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("config_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("session_name", sa.String(length=255), nullable=False),
        sa.Column("create_time", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("session_run", sa.Text(), nullable=True),
        sa.Column("session_result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """执行回滚操作"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("enemy_configs")
    op.drop_table("character_configs")
    op.drop_table("apl_configs")
    # ### end Alembic commands ###
