name: pytest

on:
  push:
    branches: [main, dev/*] # 触发分支
    tags: ["v*"]
  pull_request:
    branches: [main, dev/*]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4 # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
        shell: bash

      - name: Install dependencies with uv
        run: |
          uv sync -v

      - name: Run tests with pytest
        run: uv run pytest -v --cov=zsim --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html-${{ matrix.os }}
          path: htmlcov
